# Generated by Django 6.0 on 2026-01-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('discount_type', models.CharField(choices=[('bundle', 'Набор/комплект'), ('special', 'Специальное предложение')], default='bundle', max_length=20, verbose_name='Тип скидки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discounts/%Y/%m/%d/', verbose_name='Изображение акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала акции')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Акция активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='goods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Акция/скидка',
                'verbose_name_plural': 'Акции/скидки',
                'ordering': ['-start_date'],
            },
        ),
    ]
