# Generated by Django 6.0 on 2026-01-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='start_date',
        ),
        migrations.AddField(
            model_name='discounts',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='goods.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('bundle', 'Набор/комплект'), ('special', 'Специальное предложение')], default='special', max_length=20, verbose_name='Тип акции'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', verbose_name='Изображение'),
        ),
    ]
